export const ActionTYPES = {
  ADD_TO_CART: "ADD_TO_CART",
  DELETE_FROM_CART: "DELETE_FROM_CART",
  DELETE_ALL_FROM_CART: "DELETE_ALL_FROM_CART",
  CALCULATE_PRICE_FINAL: "CALCULATE_PRICE_FINAL",
  LOGIN_USER_DATA: "LOGIN_USER_DATA"
}